name: Comment on missing translations

concurrency:
  group: uncommented_keys-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - master

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Install Python Packages
      run: |
        pip3 install wheel
        pip3 install setuptools
        pip3 install pygithub
        pip3 install pygithub3
    - name: Update translation progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{  github.event.number }}
      run: python tools/comment_untranslated_keys.py
